---
dataset:
  data_path: /Users/pc1/Dropbox/TorchGNN_project/data_temp
  loader_name: Torchloader
  name: Torchloader
  num_node: 16
  split: exp2_test_100
exp_dir: /Users/pc1/Dropbox/TorchGNN_project/GNN_exp/|V|=16/TorchGNN_001_Torchloader_2021-Jan-16-04-18-29_train_16_(10,9,8)_64_10_att___
exp_name: TorchGNN_001_Torchloader_2021-Jan-16-04-18-29_train_16_(10,9,8)_64_10_att___
gpus:
- 0
model:
  aggregate_type: att
  degree_emb: false
  drop_prob: 0
  hidden_dim: 64
  interpol: false
  jumping: false
  loss: KL-pq
  name: TorchGNN
  num_prop: 10
  skip_connection: false
run_id: '89319'
runner: NeuralInferenceRunner
save_dir: /home/ubuntu/pycharm_project_home/GNN_exp2/WL_flex_graphs/unique_degree_shell_torch/TorchGNN_001_Torchloader_2021-Jan-16-04-18-29_train_16_(10,9,8)_64_10_att___
seed: 1234
test:
  batch_size: 1
  num_workers: 0
  test_model: /home/ubuntu/pycharm_project_home/GNN_exp2/WL_flex_graphs/unique_degree_shell_torch/TorchGNN_001_Torchloader_2021-Jan-16-04-18-29_train_16_(10,9,8)_64_10_att___/model_snapshot_best.pth
train:
  batch_size: 10
  display_iter: 13000
  is_resume: false
  lr: 0.001
  lr_decay: 0.1
  lr_decay_steps:
  - 10000
  max_epoch: 1000
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_model: None
  shuffle: true
  snapshot_epoch: 20000
  valid_epoch: 1
  wd: 0.0
use_gpu: true
